### ISSUE TITLE
fanfiction.csodaidok.hu adapter broken - Site changed

### ISSUE THREAD

**Issue by JimmXinu** [JimmXinu/FanFicFare#149]
The site fanfiction.csodaidok.hu has changed since the adapter was written and it no longer works.

This is a Hungarian language site; something the active developers cannot read.  Plus, this was found during routine testing.  No users have noticed enough to complain.

For now, I'm opening this issue as a reminder.  If somebody misses support for this site--or even better, wants to update support for it--please comment.

Otherwise, support for this site will probably go away (officially) sometime in future.

**Comment by gcomyn** [comment]
I've fixed this adapter.. even though I don't read Hungarian. I've tested it on about 5 stories.... and it works for me...

I'll send you the file in an email.

**Comment by JimmXinu** [comment]
Actually, gcomyn's changes didn't fix it completely.

At this point, assume support for this site will be removed in the next version.
